<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	#命令用$(),参数使用${}
	#包含文件
	<xacro:property name="robot_pkg" value="$(find roboticarm)">   #我的机器人包名字，保存在robot_pkg中
	<xacro:include filename="${robot_pkg}/robot_description/urdf/ur.transmission.xacro" />
	#（transmission可以简单理解为关节位置和电机相互变换的转换器）
	<xacro:include filename="${robot_pkg}/robot_description/urdf/ur.gazebo.xacro" /> # ur专用gazebo宏，空文件

	<xacro:property name="pi" value="3.14159265" /> #pi
	# 跟惯量有关的参数：质量、cog？？、DH参数
	<xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
	<xacro:property name="shoulder_mass" value="3.7000" />
	<xacro:property name="upper_arm_mass" value="8.3930" />
	<xacro:property name="forearm_mass" value="2.2750" />
	<xacro:property name="wrist_1_mass" value="1.2190" />
	<xacro:property name="wrist_2_mass" value="1.2190" />
	<xacro:property name="wrist_3_mass" value="0.1879" />

	<xacro:property name="shoulder_cog" value="0.0 0.00193 -0.02561" />
	<xacro:property name="upper_arm_cog" value="0.0 -0.024201 0.2125" />
	<xacro:property name="forearm_cog" value="0.0 0.0265 0.11993" />
	<xacro:property name="wrist_1_cog" value="0.0 0.110949 0.01634" />
	<xacro:property name="wrist_2_cog" value="0.0 0.0018 0.11099" />
	<xacro:property name="wrist_3_cog" value="0.0 0.001159 0.0" />

	<!-- Kinematic model -->
	<!-- Properties from urcontrol.conf -->
	<!--
	DH for UR5:
	a = [0.00000, -0.42500, -0.39225,  0.00000,  0.00000,  0.0000]
	d = [0.089159,  0.00000,  0.00000,  0.10915,  0.09465,  0.0823]
	alpha = [ 1.570796327, 0, 0, 1.570796327, -1.570796327, 0 ]
	q_home_offset = [0, -1.570796327, 0, -1.570796327, 0, 0]
	joint_direction = [-1, -1, 1, 1, 1, 1]
	mass = [3.7000, 8.3930, 2.2750, 1.2190, 1.2190, 0.1879]
	center_of_mass = [ [0, -0.02561, 0.00193], [0.2125, 0, 0.11336], [0.11993, 0.0, 0.0265], [0, -0.0018, 0.01634], [0, 0.0018,0.01634], [0, 0, -0.001159] ]
	-->
	# d、a
	<xacro:property name="ur5_d1" value="0.089159" />
	<xacro:property name="ur5_a2" value="-0.42500" />
	<xacro:property name="ur5_a3" value="-0.39225" />
	<xacro:property name="ur5_d4" value="0.10915" />
	<xacro:property name="ur5_d5" value="0.09465" />
	<xacro:property name="ur5_d6" value="0.0823" />

	<!-- Arbitrary offsets for shoulder/elbow joints -->
	<xacro:property name="shoulder_offset" value="0.13585" />  <!-- measured from model -->
	<xacro:property name="elbow_offset" value="-0.1197" /> <!-- measured from model -->
	# link的长度
	<!-- link lengths used in model -->
	<xacro:property name="shoulder_height" value="${ur5_d1}" />
	<xacro:property name="upper_arm_length" value="${-ur5_a2}" />
	<xacro:property name="forearm_length" value="${-ur5_a3}" />
	<xacro:property name="wrist_1_length" value="${ur5_d4 - elbow_offset - shoulder_offset}" />
	<xacro:property name="wrist_2_length" value="${ur5_d5}" />
	<xacro:property name="wrist_3_length" value="${ur5_d6}" />
	<!--property name="shoulder_height" value="0.089159" /-->
	<!--property name="shoulder_offset" value="0.13585" /-->  <!-- shoulder_offset - elbow_offset + wrist_1_length = 0.10915 -->
	<!--property name="upper_arm_length" value="0.42500" /-->
	<!--property name="elbow_offset" value="0.1197" /-->       <!-- CAD measured -->
	<!--property name="forearm_length" value="0.39225" /-->
	<!--property name="wrist_1_length" value="0.093" /-->     <!-- CAD measured -->
	<!--property name="wrist_2_length" value="0.09465" /-->   <!-- In CAD this distance is 0.930, but in the spec it is 0.09465 -->
	<!--property name="wrist_3_length" value="0.0823" /-->
	# link圆柱的半径
	<xacro:property name="shoulder_radius" value="0.060" />   <!-- manually measured -->
	<xacro:property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
	<xacro:property name="elbow_radius" value="0.060" />      <!-- manually measured -->
	<xacro:property name="forearm_radius" value="0.040" />    <!-- manually measured -->
	<xacro:property name="wrist_radius" value="0.045" />      <!-- manually measured -->

	# 创建圆柱形link的inertial 标签的宏
	<xacro:macro name="cylinder_inertial" params="radius length mass *origin">
		<inertial>
			<mass value="${mass}" />
			<xacro:insert_block name="origin" />  # insert_block允许在调用宏的时候填入一个内置的块 
			<inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
			izz="${0.5 * mass * radius * radius}" />
		</inertial>
	</xacro:macro>
	 #调用示例
	 <!-- <xacro:cylinder_inertial radius="0.06" length="0.05" mass="${base_mass}">
	       	       <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />  不一定要是origin，可以是其他属性，这里恰巧和定义的时候同名
	       </xacro:cylinder_inertial>   -->
      
       # 创建ur5机器人的宏
	<xacro:macro name="ur5_robot" params="prefix joint_limited">
		# 基连杆
		<link name="${prefix}base_link" >  
			<visual>   # 定义外观
				<geometry>  ## 形状，dae模型
					<mesh filename="package://ur_description/meshes/ur5/visual/base.dae" />
				</geometry>
				<material name="LightGrey">  ## 颜色
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision> # 定义碰撞属性
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/base.stl" />
				</geometry>
			</collision> 
			# 定义惯量 
			<xacro:cylinder_inertial radius="0.06" length="0.05" mass="${base_mass}">
				<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 肩膀-基 关节
		<joint name="${prefix}shoulder_pan_joint" type="revolute">
			<parent link="${prefix}base_link" />
			<child link = "${prefix}shoulder_link" />
			<origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
			<axis xyz="0 0 1" />  # 定义旋转轴
			# 条件语句 选择角度限制模式
			<xacro:unless value="${joint_limited}"> # unless = if not
				<limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		# 肩膀连杆
		<link name="${prefix}shoulder_link">
			<visual>
				<geometry> 
					# mesh的文件夹必须用package://格式来写，否则无法正确加载
					<mesh filename="package://ur_description/meshes/ur5/visual/shoulder.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/shoulder.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.06" length="0.15" mass="${shoulder_mass}">
				<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 上臂-肩膀 关节
		<joint name="${prefix}shoulder_lift_joint" type="revolute">
			<parent link="${prefix}shoulder_link" />
			<child link = "${prefix}upper_arm_link" />
			<origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
			<axis xyz="0 1 0" />
			<xacro:unless value="${joint_limited}">
				<limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		# 上臂 连杆
		<link name="${prefix}upper_arm_link">
			<visual>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/visual/upperarm.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/upperarm.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.06" length="0.56" mass="${upper_arm_mass}">
				<origin xyz="0.0 0.0 0.28" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 前臂-上臂 关节
		<joint name="${prefix}elbow_joint" type="revolute">
			<parent link="${prefix}upper_arm_link" />
			<child link = "${prefix}forearm_link" />
			<origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
			<axis xyz="0 1 0" />
			<xacro:unless value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		# 前臂 连杆
		<link name="${prefix}forearm_link">
			<visual>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/visual/forearm.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/forearm.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.06" length="0.5" mass="${forearm_mass}">
				<origin xyz="0.0 0.0 0.25" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 手腕1 - 前臂 关节
		<joint name="${prefix}wrist_1_joint" type="revolute">
			<parent link="${prefix}forearm_link" />
			<child link = "${prefix}wrist_1_link" />
			<origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
			<axis xyz="0 1 0" />
			<xacro:unless value="${joint_limited}">
				<limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="28.0" velocity="3.2"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		# 手腕1 连杆
		<link name="${prefix}wrist_1_link">
			<visual>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/visual/wrist1.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/wrist1.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_1_mass}">
				<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 手腕2 - 手腕1 关节
		<joint name="${prefix}wrist_2_joint" type="revolute">
			<parent link="${prefix}wrist_1_link" />
			<child link = "${prefix}wrist_2_link" />
			<origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
			<axis xyz="0 0 1" />
			<xacro:unless value="${joint_limited}">
				<limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="28.0" velocity="3.2"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		# 手腕2 连杆
		<link name="${prefix}wrist_2_link">
			<visual>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/visual/wrist2.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/wrist2.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_2_mass}">
				<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# 手腕3 - 手腕2 关节
		<joint name="${prefix}wrist_3_joint" type="revolute">
			<parent link="${prefix}wrist_2_link" />
			<child link = "${prefix}wrist_3_link" />
			<origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
			<axis xyz="0 1 0" />
			<xacro:unless value="${joint_limited}">
				<limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="28.0" velocity="3.2"/>
			</xacro:unless>
			<xacro:if value="${joint_limited}">
				<limit lower="${-pi}" upper="${pi}" effort="28.0" velocity="3.2"/>
			</xacro:if>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>
		#  手腕3 连杆 
		<link name="${prefix}wrist_3_link">
			<visual>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/visual/wrist3.dae" />
				</geometry>
				<material name="LightGrey">
					<color rgba="0.7 0.7 0.7 1.0"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://ur_description/meshes/ur5/collision/wrist3.stl" />
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_3_mass}">
				<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
			</xacro:cylinder_inertial>
		</link>
		# ee- 手腕3 关节
		<joint name="${prefix}ee_fixed_joint" type="fixed">
			<parent link="${prefix}wrist_3_link" />
			<child link = "${prefix}ee_link" />
			<origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
		</joint>
		# ee 连杆
		<link name="${prefix}ee_link">
			<collision>
				<geometry>
					<box size="0.01 0.01 0.01"/>
				</geometry>
				<origin rpy="0 0 0" xyz="-0.01 0 0"/>
			</collision>
		</link>


		# 调用转换器宏，定义转换器（引用于文件ur.transmission.xacro）
		<xacro:ur_arm_transmission prefix="${prefix}" />
		# 调用gazebo宏
		<xacro:ur_arm_gazebo prefix="${prefix}" />

		<!-- ROS base_link to UR 'Base' Coordinates transform -->
		# 固定的基base，没有属性，代表这个世界
		<link name="${prefix}base"/>
		# 基连杆与基固结 
		<joint name="${prefix}base_link-base_fixed_joint" type="fixed">
		<!-- NOTE: this rotation is only needed as long as base_link itself is not corrected wrt the real robot (ie: rotated over 180 degrees)	-->
			<origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
			<parent link="${prefix}base_link"/>
			<child link="${prefix}base"/>
		</joint>

		<!-- Frame coincident with all-zeros TCP on UR controller -->
		# 末端执行器连杆，未定义
		<link name="${prefix}tool0"/>
		# 末端执行器 - 手腕3 关节
		<joint name="${prefix}wrist_3_link-tool0_fixed_joint" type="fixed">
			<origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
			<parent link="${prefix}wrist_3_link"/>
			<child link="${prefix}tool0"/>
		</joint>

	</xacro:macro>
</robot>
